### ISSUE TITLE
Manifest for d1egoprog/triple-operations:1.0 not found

### ISSUE THREAD

**Issue by JViggiani** [d1egoprog/Text2KG#1]
Hey there, 

When I try to docker-compose this, I encounter the following error:

```
PS C:\Users\Josh\Desktop\coding\Text2KG> docker-compose -p text2kg -f deploy.yml up
[+] Running 1/1
 ✘ triple_api Error                                                                                                1.5s
Error response from daemon: manifest for d1egoprog/triple-operations:1.0 not found: manifest unknown: manifest unknown
PS C:\Users\Josh\Desktop\coding\Text2KG>
```

Has the triples repo been made private? I am somewhat new to Docker so it may be something very silly. 

Cheers.

**Comment by d1egoprog** [comment]
Hi @JViggiani

Due to some incompatibility issues with a version from the neosemantics plugin, the component was crashing and I had to take it down.  Given that, I have to take the job of releasing an improved version of the docker image along with the other improvements that were on the queue. The new version will be released soon. :) 

I am deeply sorry for the inconvenience.

**Comment by JViggiani** [comment]
Thanks for the update - on closer inspection it seems like the deploy.yml may have a typo in it. 

Line 44:

```
  triple_api:
    image: d1egoprog/triple-operations:1.0
```

Should be:

```
  triple_api:
    image: d1egoprog/triple-operations:0.1
```

Then at least people can download it and perhaps contribute. I'm going to give it a go, would you mind if I opened a pull request if I get anywhere?
